### PR TITLE
jf/graphic3d_example

### PR DESCRIPTION
**Pull request by jf---**

### CODE REVIEW

**Comment by tpaviot** [comment]
Nice. However, I have the following error:
```bash
D:\Devel\pythonocc-core\examples>python popo.py
ERROR:OCC.Display.backend:qt-pyqt4 could not be loaded
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OCC\Display\backend.py", line 100, in get_
backend
    from PyQt4 import QtCore, QtGui, QtOpenGL
ImportError: No module named PyQt4
Traceback (most recent call last):
  File "popo.py", line 11, in <module>
    display, start_display, add_menu, add_function_to_menu = init_display("qt-py
qt4")
  File "C:\Python27\lib\site-packages\OCC\Display\SimpleGui.py", line 31, in ini
t_display
    USED_BACKEND = get_backend(backend_str)
  File "C:\Python27\lib\site-packages\OCC\Display\backend.py", line 100, in get_
backend
    from PyQt4 import QtCore, QtGui, QtOpenGL
ImportError: No module named PyQt4
```
Better to leave the backend empty for those who don't have PyQt4.

**Comment by jf---** [comment]
Nice catch :+1: 
I just have this crazy pyqt bias :sunglasses:

**Comment by tpaviot** [comment]
I use both py2 and py3k. Today, anytime I code something in python, I always take care that both versions work ;)

**Comment by tpaviot** [comment]
I merged these commits into one see f57951e32e5c09fc0478397a89b393ecd175b3cf

**Comment by jf---** [comment]
Thanks, I'll do so next time in the PR...

**Pull request merged**
