### PR TITLE
Update core_modeling_sprocket.py

### PR DESCRIPTION
**Pull request by chentao807**
fix the Proxy class, it's a trick for Handle_xxx-like classes
and line 225 at @tpaviot 's branch
```
if (round_circle_2d_1.Position().Location().Coord()[1] >= 0):
```
with error
```
TypeError: 'gp_XY' object does not support indexing
```

### CODE REVIEW

**Comment by jf---** [comment]
👍

**Comment by tpaviot** [comment]
@chentao807 Be careful with modifying the line ```if (round_circle_2d_1.Position().Location().Coord()[1] >= 0):```. Since PR #322 was merged, the Coord() method returns a tuple and not a gp_XY object anymore. Please revert this change. You can have a look at travis log to check by yourself.

**Comment by tpaviot** [comment]
ok thanks @chentao807

**Comment by chentao807** [comment]
@tpaviot thanks, i fixed it.

**Pull request merged**
