### PR TITLE
be explicit about the OCE / pythonocc-core relation

### PR DESCRIPTION
**Pull request by jf---**

### CODE REVIEW

**Comment by jf---** [comment]
Thanks @tpaviot , I didnt realize there is ABI compatibility at the Patch level... cool...

**Comment by tpaviot** [comment]
@jf--- can u please update your commit ?

**Comment by jf---** [comment]
hi Thomas, 

it has been updated on jan 3rd... 
have you seen the 2nd commit?

**Comment by tpaviot** [comment]
ah ok, I missed it.

**Comment by tpaviot** [comment]
I merged these two commits into one see 69ff8fbd0bd1260fa276c621e9731cbcd5694f19

**Pull request merged**
