### PR TITLE
Major wrapper update : type hint

### PR DESCRIPTION
**Pull request by tpaviot**
What's new  in this PR:

* new ```@classnotwrapped``` and ```@methodnotwrapped``` decorators, to explicitly raise ```ClassNotWrappedError``` and ```MethodNotWrappedError```. Code and related test in commit c9ad223a063e3187d12248ef4716a94127148db6 All classes and methods skipped by the generator are not added to the SWIG file as as empty classes/methods using these decorators, for instance for the class ```ShapeFix_WireSegment``` (https://github.com/tpaviot/pythonocc-core/pull/811/files#diff-35fda90b1e486bb31490d6a762201d71R4646) or the method ```ShapeFix_Edge.Context``` (https://github.com/tpaviot/pythonocc-core/pull/811/files#diff-35fda90b1e486bb31490d6a762201d71R513)

* each c++ named enum is now available in a python proxy class. So far, enums are wrapped at the SWIG level as an integer, and can be accessed by their value, for instance:
```bash
$ python
>>> from OCC.Core.gp import *
>>> gp_Intrinsic_XZX
21
```
but there's not way to know that it is part of the ```gp_EulerSequence``` enum name, defined in c++ as
```c++
enum gp_EulerSequence
{
  //! Classic Euler angles, alias to Intrinsic_ZXZ
  gp_EulerAngles,

  [..]
  gp_Intrinsic_YZY,
  gp_Intrinsic_YXY,
  gp_Intrinsic_ZXZ,
  gp_Intrinsic_ZYZ
};
```
That's a problem, because the ```GetEulerAngles``` method of the ```gp_Quaternion``` class expects a ```gp_EulerSequence``` and, as a developer using this method, I don't know which values are availables:
```bash
>>> from OCC.Core.gp import *
>>> help(gp_Quaternion.GetEulerAngles)

Help on method gp_Quaternion_GetEulerAngles in module OCC.Core._gp:

gp_Quaternion_GetEulerAngles(...) method of OCC.Core.gp.gp_Quaternion instance
    * Returns Euler angles describing current rotation
            :param theOrder:
            :type theOrder: gp_EulerSequence
            :param theAlpha:
            :type theAlpha: float
            :param theBeta:
            :type theBeta: float
            :param theGamma:
            :type theGamma: float
            :rtype: None
```
In this PR, the gp_EulerSequence has a proxy class:
```bash
$ python
>>> from OCC.Core.gp import gp_EulerSequence
>>> dir(gp_EulerSequence)
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'gp_EulerAngles', 'gp_Extrinsic_XYX', 'gp_Extrinsic_XYZ', 'gp_Extrinsic_XZX', 'gp_Extrinsic_XZY', 'gp_Extrinsic_YXY', 'gp_Extrinsic_YXZ', 'gp_Extrinsic_YZX', 'gp_Extrinsic_YZY', 'gp_Extrinsic_ZXY', 'gp_Extrinsic_ZXZ', 'gp_Extrinsic_ZYX', 'gp_Extrinsic_ZYZ', 'gp_Intrinsic_XYX', 'gp_Intrinsic_XYZ', 'gp_Intrinsic_XZX', 'gp_Intrinsic_XZY', 'gp_Intrinsic_YXY', 'gp_Intrinsic_YXZ', 'gp_Intrinsic_YZX', 'gp_Intrinsic_YZY', 'gp_Intrinsic_ZXY', 'gp_Intrinsic_ZXZ', 'gp_Intrinsic_ZYX', 'gp_Intrinsic_ZYZ', 'gp_YawPitchRoll']
>>> gp_EulerSequence.gp_Intrinsic_XZX
21
```
The old way to access values is still available though.
```bash
>>> gp_Intrinsic_XZX
21
```

* docstrings moved to numpydoc style, which is more readable.
Before:
```Help on built-in function gp_Pnt_BaryCenter in module OCC.Core._gp:

gp_Pnt_BaryCenter(...)
    * Assigns the result of the following expression to this point (Alpha*this + Beta*P) / (Alpha + Beta)
            :param Alpha:
            :type Alpha: float
            :param P:
            :type P: gp_Pnt
            :param Beta:
            :type Beta: float
            :rtype: None
```
After:
```bash
Help on function BaryCenter in module OCC.Core.gp:

BaryCenter(self, *args) -> 'void'
    Assigns the result of the following expression to this point (alpha*this + beta*p) / (alpha + beta).
    
    Parameters
    ----------
    Alpha: float
    P: gp_Pnt
    Beta: float
    
    Returns
    -------
    None
```
* fix docstrings for wrapped c++ method that return values by parameter. For instance, the docstring for ```gp_Quaternion.GetEulerAngles``` was
```bash
gp_Quaternion_GetEulerAngles(...)
    * Returns Euler angles describing current rotation
            :param theOrder:
            :type theOrder: gp_EulerSequence
            :param theAlpha:
            :type theAlpha: float
            :param theBeta:
            :type theBeta: float
            :param theGamma:
            :type theGamma: float
            :rtype: None
```
where this function actually *returns* 3 floats, it's now fixed:
```bash
GetEulerAngles(self, *args) -> 'void'
    Returns euler angles describing current rotation.
    
    Parameters
    ----------
    theOrder: gp_EulerSequence
    
    Returns
    -------
    theAlpha: float
    theBeta: float
    theGamma: float
```

* finally, stub .pyi files containing type hints have been added to the wrapper. Stub files are used by mypy for type checking or PyCharm for type introspection and auto-completion.

### CODE REVIEW

**Comment by tpaviot** [comment]
@jf--- could u please review this PR ?

**Comment by tpaviot** [comment]
Some recent changes related to mypy, see the discussion https://gitter.im/python/typing#

PyCharm can use pyi stubfiles for autocompletion or code suggestion that mypy cannot handle. Th eidea is that .pyi pythonocc-core files are consistent with both, thats' the ongoing work

**Comment by jf---** [comment]
hi @tpaviot, I've searched on `anaconda.org`, as I recall that PR's resulted in a conda build?

For a recent project, I've integrated running a mypy check, that might be an idea.

the github workflow looks something like:

```
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  mypy-check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Mypy Check
        uses: jpetrucciani/mypy-check@0.761
        with:
          # File or directory to run mypy on
          #path: some_directory # optional, default is .

```

**Comment by tpaviot** [comment]
@jf--- no, since I moved to Azure CI, there's not automatic upload to anaconda anymore, but that's something I can add back. I added a mypy check at the end of the build (mypy check for two of the scripts that are part of the unittest). So far this test doesn't pass because I did not finish yet the work related to stub files.

**Comment by jf---** [comment]
>  there's not automatic upload to anaconda anymore, but that's something I can add back

I thought it was an incredible luxury, I think that would be wonderful...

>  I've integrated running a mypy check

You can [see it here](https://github.com/jf---/pythonocc-core/actions/). 
It'll typecheck the python code not generated by `pythonocc-generator`, and check the imported typehints via the .pyi file...

This is just a quick sketch of what I think I can contribute.
That and adding types to the non-generated python code

***

Hmm, I think the `@overload` decorator is required for the `Perform` method as well?


```
class Geom2dInt_IntConicCurveOfGInter(IntRes2d_Intersection):
	@overload
	def __init__(self) -> None: ...
	@overload
	def __init__(self, L: gp_Lin2d, D1: IntRes2d_Domain, PCurve: Adaptor2d_Curve2d, D2: IntRes2d_Domain, TolConf: float, Tol: float) -> None: ...
	@overload
	def __init__(self, C: gp_Circ2d, D1: IntRes2d_Domain, PCurve: Adaptor2d_Curve2d, D2: IntRes2d_Domain, TolConf: float, Tol: float) -> None: ...
	@overload
	def __init__(self, E: gp_Elips2d, D1: IntRes2d_Domain, PCurve: Adaptor2d_Curve2d, D2: IntRes2d_Domain, TolConf: float, Tol: float) -> None: ...
	@overload
	def __init__(self, Prb: gp_Parab2d, D1: IntRes2d_Domain, PCurve: Adaptor2d_Curve2d, D2: IntRes2d_Domain, TolConf: float, Tol: float) -> None: ...
	@overload
	def __init__(self, H: gp_Hypr2d, D1: IntRes2d_Domain, PCurve: Adaptor2d_Curve2d, D2: IntRes2d_Domain, TolConf: float, Tol: float) -> None: ...
	def Perform(self, L: gp_Lin2d, D1: IntRes2d_Domain, PCurve: Adaptor2d_Curve2d, D2: IntRes2d_Domain, TolConf: float, Tol: float) -> None: ...
	def Perform(self, C: gp_Circ2d, D1: IntRes2d_Domain, PCurve: Adaptor2d_Curve2d, D2: IntRes2d_Domain, TolConf: float, Tol: float) -> None: ...
	def Perform(self, E: gp_Elips2d, D1: IntRes2d_Domain, PCurve: Adaptor2d_Curve2d, D2: IntRes2d_Domain, TolConf: float, Tol: float) -> None: ...
	def Perform(self, Prb: gp_Parab2d, D1: IntRes2d_Domain, PCurve: Adaptor2d_Curve2d, D2: IntRes2d_Domain, TolConf: float, Tol: float) -> None: ...
	def Perform(self, H: gp_Hypr2d, D1: IntRes2d_Domain, PCurve: Adaptor2d_Curve2d, D2: IntRes2d_Domain, TolConf: float, Tol: float) -> None: ...
```

**Comment by jf---** [comment]
same thing, with `staticmethods`

```python
	@staticmethod
	def NbSamples(self, C: Adaptor2d_Curve2d) -> int: ...
	@staticmethod
        >>> missing @overload
	def NbSamples(self, C: Adaptor2d_Curve2d, U0: float, U1: float) -> int: ...
```

**Comment by tpaviot** [comment]
@jf--- yes, right. I implemented the @overload decorator for constructors only, I was not sure it would be required for other methods

**Comment by jf---** [comment]
@tpaviot oh wow, that was quick...

It looks like there are some reference errors / missing objects:

```
Aspect_TypeOfColorScaleData
Aspect_VKeyMouse
PrsMgr_PresentationManager3d
PrsMgr_Presentation
```

There still are quite some references to `PrsMgr_Presentation` for instance also in some of the utility packages ( a lot of improvements on the graphics front since v7 ) 

Also it seems that `Enum` classes are not yet imported into the `.pyi` file?

image


https://github.com/tpaviot/pythonocc-core/blob/b928a3e3faed1eadbf917d647ff77339d4dc9cc3/src/SWIG_files/wrapper/AIS.pyi#L457-L460

**Comment by tpaviot** [comment]
@jf--- all of the 
```
Aspect_TypeOfColorScaleData
Aspect_VKeyMouse
PrsMgr_PresentationManager3d
PrsMgr_Presentation
```
are part of their respective .pyi file, and enum are also in the .pyi file. I'm not sure you have to open the .pyi file directly in PyCharm. They are loaded automatically when you import the python package.

**Comment by tpaviot** [comment]
@jf--- here's my PyCharm window interface

capt_ais_prs

**Comment by tpaviot** [comment]
Build is fixed, mypy basic test passes, now I have to ensure a ```mypy --strict``` test also passes.

**Comment by tpaviot** [comment]
Ran mypy for the first time over a pythonocc script, result here https://github.com/tpaviot/pythonocc-demos/commit/f3ea9b4f65a9dff482be04b153d4ce5ec2430e13

**Pull request merged**
