### PR TITLE
jf/volume_maker_boolop_example

### PR DESCRIPTION
**Pull request by jf---**
continued discussion
https://github.com/tpaviot/pythonocc-core/issues/162

### CODE REVIEW

**Comment by jf---** [comment]
[example for #162 ](https://github.com/tpaviot/pythonocc-core/issues/162)

**Comment by tpaviot** [comment]
@jf--- Geometries used in this example are too complex. First work with cylinders, boxes etc. then move to something more complex

**Comment by tpaviot** [comment]
@jf--- This feature is currently not being supported by pythonocc-0.17.

**Comment by jf---** [comment]
@tpaviot , understood, closing PR

**Pull request closed without merging**
