### PR TITLE
Review/travis anaconda upload

### PR DESCRIPTION
**Pull request by tpaviot**
Automatic upload binaries to anaconda cloud repository http://anaconda.org/tpaviot/pythonocc-core

@jf--- and @rainman110 any suggestion/comment ?

### CODE REVIEW

**Comment by rainman110** [comment]
Isn't there already another pythonocc repository at https://anaconda.org/pythonocc?

**Comment by tpaviot** [comment]
@jf--- created this repository a while ago. I did not really understand how to upload contents using a token to shared repositories. By default it uploads to /tpaviot. I went on with this repository. I can try to change the token so that it uploads to pythonocc.

**Comment by tpaviot** [comment]
@rainman110 I took time to think about that. Here is what I suggest:

* let  https://anaconda.org/pythonocc be the official repository for all pythonocc related stuff. I will *manually* move the 0.17.1 packages from /tpaviot to /pythonocc

* I keep using the /tpaviot repository to test/experiment/fix nightly builds and automatic updates. As a consequence, so far, I leave the current PR as is ;

* as soon as the nightly builds/automatic updates are ok and proved to be robust, I will move the target repository from /tpaviot to /pythonocc

So in brief /tpaviot is an experimental repository whereas /pythonocc is the official one. Are you @jf--- and @rainman110 ok with that ?

**Comment by tpaviot** [comment]
done. All packages moved to /pythonocc, removed from /tpaviot

**Comment by rainman110** [comment]
@tpaviot I think this is a good workflow. I have no problems with it.

**Comment by jf---** [comment]
perfect! I think the split between experimental ( -> /tpaviot ) and production packages ( -> /pythonocc ) is a good idea... since its explicit what can be expected ( polished vs WIP )

Awesome!

So is the idea that every commit to **/master** is now a micro release?
By that I mean, Major, Minor, Patch, Micro, as in 0.17.1.SHA1_hash

**Comment by tpaviot** [comment]
@jf--- The idea is to have a nightly build of the master branch (currently set up to be triggered each day 7.00 paris time) which is uploaded to /tpaviot. Not every single commit to master will trigger an upload. There might be a long time between two changes to the master branch (let's say one month). One can argue that it's not necessary to compile/upload each night something that does not change for a month, but I discovered it's important to regularly trigger travis/conda builds to check that updates to travis and/or conda do not ceate any regression to our build process.

**Comment by jf---** [comment]
understood, thanks for pointing out your thinking here...

**Pull request merged**
