### PR TITLE
Adding PyQt5 support

### PR DESCRIPTION
**Pull request by tpaviot**
Refactoring/fixes over @jf---:jf/pyqt5 branch.

### CODE REVIEW

**Comment by tpaviot** [comment]
@jf--- Please test:

* I fixed pep8 issues

* rebased branch on top of master to benefit from travis check

* Fixed global variable issues (ie removed global var everywhere it's not required)

* updated travis build

I checked it's ok on win32/64 with both py2 and py3k.

**Comment by jf---** [comment]
tested all backends on osx / py27 
tested the core_visualization_overpaint_viewer.py
a nr of other examples...

All looking good... :+1:

**Comment by tpaviot** [comment]
ok, let me merge this branch, and release pythonocc-0.16.3

**Comment by jf---** [comment]
@tpaviot, wooohoooo

**Pull request merged**
