### PR TITLE
review/qt-fixes

### PR DESCRIPTION
**Pull request by jf---**
a fresh PR from feedback of PR #69

### CODE REVIEW

**Comment by tpaviot** [comment]
@jf--- you should rebase on top of review/qt-fixes and resolve conflicts

**Comment by tpaviot** [comment]
@jf--- I cherry-picked your changes, and cleaned-up a bit the commits (PEP8, PySide). This PR is not required anymore. Please update review/qt-fixes and test. The example works on my machine but the display flickers.

**Comment by tpaviot** [comment]
yes, flickering appears in rotate mode. In static mode it's just perfect.

For the landscape score, AFAIK allowed dependencies are django and another package. I did not manage to add wxPython or PyQt as dependencies.

**Comment by tpaviot** [comment]
@jf--- I'm wrong, there's flickering in both modes (static and rotate modes)

**Comment by jf---** [comment]
Hmmm... I only have the flickering when rotating... 
Why, I can only guess... perhaps differences in Qt ( I use Qt 4.8.6  and PyQt4 4.10 )
Thing is that its not that visible to see in a screencast recording ;(

Its up to you -- possible you could merge the changes the qtDisplay, these are fine and leave the example out, since its imperfect.

**Comment by tpaviot** [comment]
I tested on Linux, it works fine. It certainly coming from something related to my machine or graphic driver. On Linux too, flickering occurs when rotating the box, shift selecting, or move another window on top of it causing a refresh. Let me close this PR, create another one with the fixed commits and merge into master. We'll see later how to fix these flickering issues.

**Pull request closed without merging**
