### PR TITLE
review/occt7x support

### PR DESCRIPTION
**Pull request by tpaviot**
@rainman110 Branch update to latest occt 740 release. Below is the current tests status. There are unusual memory issues, related to the new handle implementation ?

Tests only on Linux so far.
```
testAutoImportOfDependentModules (core_wrapper_features_unittest.TestWrapperFeatures)
Test: automatic import of dependent modules ... FAIL
testProtectedConstructor (core_wrapper_features_unittest.TestWrapperFeatures)
Test: protected constructor ... ok
testStandardBooleanByRefPassedReturned (core_wrapper_features_unittest.TestWrapperFeatures) ... ok
testTopoDS_byref_arguments (core_wrapper_features_unittest.TestWrapperFeatures) ... ok
test_array_iterator (core_wrapper_features_unittest.TestWrapperFeatures) ... ok
test_const_Standard_Integer_byref (core_wrapper_features_unittest.TestWrapperFeatures) ... ok
test_const_Standard_Real_byref (core_wrapper_features_unittest.TestWrapperFeatures) ... ok
test_default_constructor_DEFINE_STANDARD_ALLOC (core_wrapper_features_unittest.TestWrapperFeatures)
OCE classes the defines standard alllocator can be instanciated ... ok
test_deprecation_downcasts (core_wrapper_features_unittest.TestWrapperFeatures) ... ok
test_deprecation_get_handle (core_wrapper_features_unittest.TestWrapperFeatures)
Handles are now completely transparent. The GetHandle method is ... ok
test_deprecation_get_object (core_wrapper_features_unittest.TestWrapperFeatures)
Handles are now completely transparent. The GetObject method is ... ok
test_deprecation_handle_class (core_wrapper_features_unittest.TestWrapperFeatures)
Handles are now completely transparent. The Handle_* constructor is ... ok
test_deprecation_warning (core_wrapper_features_unittest.TestWrapperFeatures)
since pythonocc-0.18.2. import OCC.* changed to import OCC.Core.* ... ok
test_dict (core_wrapper_features_unittest.TestWrapperFeatures) ... ok
test_downcast_curve (core_wrapper_features_unittest.TestWrapperFeatures)
Test if a GeomCurve can be DownCasted to a GeomLine ... FAIL
swig/python detected a memory leak of type 'opencascade::handle< Geom_Curve > *', no destructor found.
test_dump_to_string (core_wrapper_features_unittest.TestWrapperFeatures) ... ok
test_eq_operator (core_wrapper_features_unittest.TestWrapperFeatures) ... ok
test_ft1 (core_wrapper_features_unittest.TestWrapperFeatures)
Test: Standard_Integer & by reference transformator ... ok
test_gp_Quaternion (core_wrapper_features_unittest.TestWrapperFeatures) ... ok
test_gp_Vec_operators (core_wrapper_features_unittest.TestWrapperFeatures) ... ok
test_handle_standard_transient_copy (core_wrapper_features_unittest.TestWrapperFeatures) ... ok
test_handling_exceptions (core_wrapper_features_unittest.TestWrapperFeatures)
asserts that handling of OCC exceptions is handled correctly in pythonocc ... ok
test_hash (core_wrapper_features_unittest.TestWrapperFeatures) ... ok
test_hash_eq_operator (core_wrapper_features_unittest.TestWrapperFeatures)
test that the == wrapper is ok ... ok
test_in_place_operators (core_wrapper_features_unittest.TestWrapperFeatures) ... ok
test_inherit_topods_shape (core_wrapper_features_unittest.TestWrapperFeatures) ... ok
test_list (core_wrapper_features_unittest.TestWrapperFeatures) ... ok
test_local_properties (core_wrapper_features_unittest.TestWrapperFeatures)
Get and modify class local properties ... ok
test_memory_handle_getobject (core_wrapper_features_unittest.TestWrapperFeatures) ... ERROR
test_neq_operator (core_wrapper_features_unittest.TestWrapperFeatures) ... ok
test_pickle_from_file (core_wrapper_features_unittest.TestWrapperFeatures) ... ok
test_repr_for_null_topods_shapes (core_wrapper_features_unittest.TestWrapperFeatures) ... ERROR
test_repr_overload (core_wrapper_features_unittest.TestWrapperFeatures)
Test if repr string is properly returned ... FAIL
test_return_enum (core_wrapper_features_unittest.TestWrapperFeatures)
Check that returned enums are properly handled, wether they're returned ... FAIL
test_shape_conversion_as_py_none (core_wrapper_features_unittest.TestWrapperFeatures) ... FAIL
test_standard_boolean_byref (core_wrapper_features_unittest.TestWrapperFeatures) ... ERROR
test_standard_integer_by_ref_passed_returned (core_wrapper_features_unittest.TestWrapperFeatures) ... ok
test_static_method (core_wrapper_features_unittest.TestWrapperFeatures) ... ok
test_sub_class (core_wrapper_features_unittest.TestWrapperFeatures)
Test: subclass ... ok
test_topology (core_wrapper_features_unittest.TestWrapperFeatures) ... ok
test_traverse_box_topology (core_wrapper_features_unittest.TestWrapperFeatures) ... ok
test_axis (core_geometry_unittest.TestGeometry)
Test: axis ... ok
test_bezier_surfaces (core_geometry_unittest.TestGeometry)
Test: Bezier surfaces ... ERROR
test_bspline (core_geometry_unittest.TestGeometry)
Test: bspline ... ok
test_circles2d_from_curves (core_geometry_unittest.TestGeometry)
Test: circles2d from curves ... FAIL
test_curves2d_from_curves (core_geometry_unittest.TestGeometry)
Test: curves 2d from curves ... ERROR
test_curves2d_from_offset (core_geometry_unittest.TestGeometry)
Test: curves 2d from offset ... ERROR
test_distances (core_geometry_unittest.TestGeometry)
Test: distances ... Erreur de segmentation (core dumped)
```

### CODE REVIEW

**Comment by rainman110** [comment]
Oh... According to the tests, there are still some major issues. Inheritance does not work correctly, handles as well. I'll have a look into it.

**Comment by rainman110** [comment]
@tpaviot Had a quick look to it. One major problem seems to be wrong (missing) imports! for example, BRepBuilderAPI must import Geom.i, but does not do it in your code.

I'd like to have compiler error, when we miss imports, but i dont know how to do it. The best is to really enable warnings. Then we should at least see, when some argument type is not known.

**Comment by rainman110** [comment]
@tpaviot I made a new PR that should fix your problems.

**Comment by tpaviot** [comment]
I close this PR, outdated.

**Pull request closed without merging**
