### PR TITLE
Install swig modules properly

### PR DESCRIPTION
**Pull request by rainman110**
By installing the modules instead of copying them, cmake can do its magic and set the rpaths correctly.

This should fix issue https://github.com/tpaviot/pythonocc-core/issues/324. 

Note: I am currently assuming, that the library dependencies are all installed in ```${CMAKE_INSTALL_PREFIX}/lib```. This can be different on rpm based systems (i.e. lib64). It would be good, if we could additionally provide a cmake configuration value, where we can set/override the library path manually.

### CODE REVIEW

**Comment by tpaviot** [comment]
@rainman110 Does it change anything to the cmake min required version ?

**Comment by rainman110** [comment]
@tpaviot Not that I know. Setting the variables should be no problem, even if cmake does not know them. The install(TARGETS... ) thing should also be working.

But I haven't tried to use it with an old (2.6) cmake I have to admit. Would it harm, to force a cmake 2.8.12 or something? This is already pretty old I think.

**Comment by tpaviot** [comment]
Currently, the minimum cmake required version is 2.6 but we can move up to 2.8 of course

**Comment by jf---** [comment]
+1 for using recent CMake versions, 3.5 is the current one

**Pull request merged**
