### PR TITLE
Review/smesh 6.5.3.1 support

### PR DESCRIPTION
**Pull request by jf---**
SMESH works well, and I dont any reason not to merge this brach?
@tpaviot, what's keeping us from doing so?

### CODE REVIEW

**Comment by tpaviot** [comment]
Delayed

**Comment by jf---** [comment]
hi @tpaviot ,

Why was this PR deleted? SMESH is pretty important IMHO...

**Comment by tpaviot** [comment]
@jf--- smesh has to be checked/updated first.

**Comment by jf---** [comment]
hi @tpaviot , I've just submitted a PR for this...
looking fwd getting SMESH back on track :tropical_drink:

**Comment by crobarcro** [comment]
I'd like to help test smesh support, is there any branch available with smesh support enabled? I've build pythonOCC 17.1 and the dev sources from the tpaviot/SMESH repo, I'm keen to test the wrappers if possible.

**Comment by tpaviot** [comment]
There have been some changes tin smesh recently, the pythonocc-wrapper needs to be updated. Note that smesh now requires oce-0.17 or oce-0.17.1

**Comment by crobarcro** [comment]
Thanks, I've actually been trying to build it with various combinations, for example, I've built oce 16, the old review branch 'review/smesh-6.5.3.1-support' from Jelle Feringa's fork and his fork of smesh. actually I got all this to build and link, but when I try to import in python I get:

``` python
In [1]: import OCC.SMESH
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-ea8798812cbd> in <module>()
----> 1 import OCC.SMESH

/usr/lib/python2.7/dist-packages/OCC/SMESH.py in <module>()
    140 import OCC.TopLoc
    141 import OCC.TopAbs
--> 142 import OCC.SMESHDS
    143 import OCC.SMDS
    144 import OCC.TopTools

/usr/lib/python2.7/dist-packages/OCC/SMESHDS.py in <module>()
    132 SwigPyIterator_swigregister(SwigPyIterator)
    133 
--> 134 import OCC.SMDS
    135 import OCC.SMDSAbs
    136 import OCC.TopoDS

/usr/lib/python2.7/dist-packages/OCC/SMDS.py in <module>()
    385 SMDS_IteratorOfElements_swigregister(SMDS_IteratorOfElements)
    386 
--> 387 class SMDS_Mesh(object):
    388     thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    389     __repr__ = _swig_repr

/usr/lib/python2.7/dist-packages/OCC/SMDS.py in SMDS_Mesh()
    436 
    437 
--> 438     def elementsIterator(self, type=SMDSAbs_All):
    439         """
    440         :param type: default value is SMDSAbs_All

NameError: name 'SMDSAbs_All' is not defined

```

Is there any combination that would let me start playing around with smesh (e.g. an old smesh branch that works with oce 16 and that review branch)?

**Pull request closed without merging**
