### PR TITLE
DisplayVector method was broken due to a subtle missed API change

### PR DESCRIPTION
**Pull request by jf---**
DisplayVector method was broken due to a subtle missed API change

### CODE REVIEW

**Comment by tpaviot** [comment]
@jf---  Is there an example in our list where I could check the fix works ?

**Comment by jf---** [comment]
Sure:

```python
from OCC.Display.SimpleGui import init_display
from OCC.gp import *
display, start_display, add_menu, add_function_to_menu = init_display()
display.DisplayVector(gp_Vec(100,0,0), gp_Pnt())
start_display()
```

**Comment by tpaviot** [comment]
-1 gp_Vec should be imported at the beginning of occviewer

**Comment by tpaviot** [comment]
@jf--- On my windows machine, only the cone is drawn, not the arrow body. Can you paste a screenshot of what you get on your mac ?

**Comment by tpaviot** [comment]
@jf--- up

**Comment by tpaviot** [comment]
@jf--- could you get the example work ?

**Comment by jf---** [comment]
created another PR for this...
yep, example works, and alas, I checked the C++ code,  its just the Cone being drawn... too bad...

**Comment by tpaviot** [comment]
@jf--what do you mean exactly with "yes the example works" and "only the cone being drawn". If only the cone is drawn, the example actually doesn't work imo

**Comment by jf---** [comment]
so I read the C++ code and there is no body to render, its "just" the cone... ( -> its an ugly vector, but comes in handy... )

**Comment by tpaviot** [comment]
ok, I got it

**Pull request merged**
