### PR TITLE
fixes #225

### LINKED ISSUE #225: the PyQt4.QtCore and PyQt5.QtCore modules both wrap the QObject class
I installed python-occ in Archlinux from here: https://aur.archlinux.org/packages/python-occ/ 
It built correctly but when I try to run the basic example in the web site ( http://www.pythonocc.org/quick-examples/hello-dumb-box/ ) I get the following error:

```
from OCC.Display.SimpleGui import init_display

from OCC.BRepPrimAPI import BRepPrimAPI_MakeBox

display, start_display, add_menu, add_function_to_menu = init_display()
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-3-7053f85cee0b> in <module>()
----> 1 display, start_display, add_menu, add_function_to_menu = init_display()

/usr/lib/python3.5/site-packages/OCC/Display/SimpleGui.py in init_display(backend_str, size)
    139         if not app:  # create QApplication if it doesnt exist
    140             app = QtWidgets.QApplication(sys.argv)
--> 141         win = MainWindow()
    142         win.show()
    143         win.canva.InitDriver()

/usr/lib/python3.5/site-packages/OCC/Display/SimpleGui.py in __init__(self, *args)
     93             def __init__(self, *args):
     94                 QtWidgets.QMainWindow.__init__(self, *args)
---> 95                 self.canva = qtViewer3d(self)
     96                 self.setWindowTitle("pythonOCC-%s 3d viewer ('%s' backend)" % (VERSION, used_backend))
     97                 self.resize(size[0], size[1])

/usr/lib/python3.5/site-packages/OCC/Display/qtDisplay.py in __init__(self, *kargs)
    108 class qtViewer3d(qtBaseViewer):
    109     def __init__(self, *kargs):
--> 110         qtBaseViewer.__init__(self, *kargs)
    111         self._drawbox = False
    112         self._zoom_area = False

/usr/lib/python3.5/site-packages/OCC/Display/qtDisplay.py in __init__(self, parent)
     68 
     69         self._have_pyside = have_pyside()
---> 70         self._have_pyqt4 = have_pyqt4()
     71         self._have_pyqt5 = have_pyqt5()
     72         self._have_backend = have_backend()

/usr/lib/python3.5/site-packages/OCC/Display/backend.py in have_pyqt4()
     35     global HAVE_PYQT4, QtCore, QtGui, QtWidgets, QtOpenGL
     36     try:
---> 37         from PyQt4 import QtCore, QtGui, QtOpenGL
     38         QtWidgets = QtGui
     39         HAVE_PYQT4 = True

RuntimeError: the PyQt4.QtCore and PyQt5.QtCore modules both wrap the QObject class
```

### PR DESCRIPTION
**Pull request by jf---**
fixes #225

### CODE REVIEW

**Comment by tpaviot** [comment]
According to me the ````have_pyqt5```` function name is confusing. Indeed it can returns ````False```` even if PyQt5 is installed. So with your fix, the function name should be changed to "load_pyqt5", "load_pyqt4" or something like that.

**Comment by jf---** [comment]
hi @tpaviot , your're right on, see new commit...

**Comment by tpaviot** [comment]
@jf--- GUI tests don't pass on Linux see https://travis-ci.org/tpaviot/pythonocc-core/jobs/121359117

**Comment by jf---** [comment]
hi @tpaviot , yikes, updated...

**Pull request merged**
