### PR TITLE
AIS_ColoredShape example

### PR DESCRIPTION
**Pull request by jf---**
show how to render subshapes with a different color, utilizing OCE 0.17 new AIS_ColoredShape class

### CODE REVIEW

**Comment by jf---** [comment]
anything stopping you from merging?

**Comment by tpaviot** [comment]
I proceed PR by PR, step by step, didn't review this one yet

**Comment by jf---** [comment]
Bump...

**Comment by tpaviot** [comment]
@jf--- You should take care to rebase your branch when submitting a PR. Indeed this branch should only include commit ffccbb0 (the laste one, related to AIS_ColoredShape).

I rebased tmp-oce-0.17 onto latest master, to benefit from automatic examples, cherry-picked the AIS_Colored shape commit, and fixed the example see commit c656c4cd15e0eac487ba1d2447d7820f7a20ba94

**Comment by jf---** [comment]
hi @tpaviot , sorry for the incorrect HEAD version & thanks for rebasing!

**Pull request closed without merging**
