### PR TITLE
Review/meshds numpy

### PR DESCRIPTION
**Pull request by tpaviot**

### CODE REVIEW

**Comment by tpaviot** [comment]
@kleinsimon Thank you for your contribution. Can you please have a look at this PR? Can you please contribute an example using the two methods you added?

**Comment by kleinsimon** [comment]
@tpaviot thank you for merging, I will create a pull request in the demo repo

**Comment by kleinsimon** [comment]
This is working really sweet. I wanted to put an example with a material assigned to the mesh, but could not get the mesh_vs to show anything other than the edges. Do you have an idea, what might be missing? I tried to put the material into the constructed MeshVS_MeshPrsBuilder, but there seems to be no shader for the faces.

**Comment by kleinsimon** [comment]
Ok I have added a working example for a MeshDS with numpy and a surface material. There were two pitfalls:

- SetDisplayMode of MeshVS_Mesh expected not AIS_DisplayMode but MeshVS_DisplayModeFlags (somehow obvious now). So for shaded, the value is 2 not 0
- directly setting the material to the MeshVS_Mesh object had no effect, it had to be set to the drawer of the builder. 

I have now created 4 examples and sent a pull-request in the demo repo

**Comment by tpaviot** [comment]
@kleinsimon Great, thank you. Let me switch to the other repo and test/report feedbacks

**Pull request merged**
