### PR TITLE
jf/opengl-ffp-vs-shader-pipeline-flags

### PR DESCRIPTION
**Pull request by jf---**
to utilize GLSL shaders, the OpenGL pipeline requires to be initialized with OpenGL API 2 ( shader ) rather than OpenGL API 1 ( fixed function pipeline FFP )
these days, FFP is legacy and not (well) maintained by graphics drivers... 
using the Shader API by default is a good idea IMO

### CODE REVIEW

**Comment by jf---** [comment]
This WIP requires some love and attention from a person more well versed in C++ than myself ( not a C++ dev at all ). That said, this surely points in the right direction ;)

**Comment by tpaviot** [comment]
@jf--- Ok, I will work from your 2 branches to make only one related to glsl, both the example and the changes in the c++ display code.

**Comment by jf---** [comment]
Thanks @tpaviot , so the previous branch had GLSL & C++ mixed up, this branch is a little cleaner and "just" the C++ updates...

**Comment by tpaviot** [comment]
@jf--- These c++ changes seem to be necessary to run the GLSL example. I'd like the commits from the other branch to be available in this one, so that I can check that the required changes to Display3d.cpp actually enable GLSL features (currently I'm not convinced about that).

**Comment by jf---** [comment]
@tpaviot you mean the #315 branch, right, the WIP shader example?

**Comment by tpaviot** [comment]
@jf--- yes

**Comment by jf---** [comment]
so on the left is GLSL, the hilight is a little more wet looking...

image

**Comment by jf---** [comment]
```python
INFO:OCC.Display.backend:backend loaded: qt-pyqt5
INFO:OCC.Display.SimpleGui:GUI backend set to: qt-pyqt5
 ###### 3D rendering pipe initialisation #####
Display3d class initialization starting ...
Aspect_DisplayConnection created.
Graphic_Driver created.
V3d_Viewer created.
AIS_InteractiveContext created.
V3d_View created
Cocoa window created.
fixed function pipeline enabled? 0
no buffer swap enabled? 0
print glsl warnings? 1
V3d_Viewer created.
V3d_View created
AIS_InteractiveContext created.
Display3d class successfully initialized.
 ########################################
TKOpenGl | Type: Portability | ID: 0 | Severity: Low | Message:
  GLSL linker log:
WARNING: Could not find vertex shader attribute 'occTexCoord' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'occVertColor' to match BindAttributeLocation request.

TKOpenGl | Type: Portability | ID: 0 | Severity: Low | Message:
  GLSL linker log:
WARNING: Could not find vertex shader attribute 'occNormal' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'occTexCoord' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'occVertColor' to match BindAttributeLocation request.

ref count  0
```

**Comment by jf---** [comment]
looks like shader vars arent accesible for the moment ( not trying to overwhelm, but document @tpaviot  😉  )

```python
glsl_vars = aProgram.Variables()
# Out[2]: <Swig Object of type 'NCollection_Sequence< Handle_Graphic3d_ShaderVariable > *' at 0x1158bc330>
```

**Comment by tpaviot** [comment]
@jf--- did you rebase on top of master ? Handle_Graphic3d_ShaderVariable should be available

**Comment by tpaviot** [comment]
@jf--- Nice screenshot, although I don't think the sphere is the most suitable geometry to demonstrate shader effects

**Comment by jf---** [comment]
hi @tpaviot ,

turns out that little is happening when Phong shading is not available. Somehow ( and this is __bad__ we're still using gouraud by default 💩  ) 

```python
display.View.SetShadingModel(V3d_PHONG)
```

fixes this....

image

**Comment by tpaviot** [comment]
@jf--- what's the status of this branch ? is it ready to be reviewed/refactored or is is still wip ?

**Comment by jf---** [comment]
ready for review, it basically does the job, but the status of how well or not GLSL is actually working is unclear to me. it would be useful to be able to trace the OpenGL execution, I've been looking into that a little but its quite a daunting topic.

**Comment by tpaviot** [comment]
So I suggest to be careful with this PR before merging. Changes to Display3d and Opengl stuff has caused serious issues in the past (I mean I lost a lot of time debugging this part). Many tests should be run, on different machines, OSes, graphic cards, we absolutely need to avoid any regression

**Comment by jf---** [comment]
@tpaviot , absolutely! so this is WIP, not ready for merging at *all*

**Comment by jf---** [comment]
hi @tpaviot , this is a pretty interesting read on the topic of [FFP vs programmable shader pipeline](https://dev.opencascade.org/index.php?q=node/1173)

**Comment by jf---** [comment]
@tpaviot , shall we push this for the coming 0.17.1 release?
with all of the recent changes, this is probably much closer to complete...
it would be a serious feature for the viewer & the examples are here...
what do you think?

**Comment by tpaviot** [comment]
@jf--- I guess this PR can be closed ?

**Comment by jf---** [comment]
not really, being able to set the fixed-function-pipeline vs the shader pipeline is relevant, as is having the swap-buffer flag...

will re-open another PR to keep things simpler ;)

**Pull request closed without merging**
