### PR TITLE
improved default tesselation, face boundaries drawn by default, selection orange by default, phong shading by default.

### LINKED ISSUE #328: enable phong shading by default
smoother hilights, performs interpolation of the normals where the vertices meet

image

### PR DESCRIPTION
**Pull request by jf---**
improved default tesselation, face boundaries drawn by default, selection orange by default, phong shading by default.

fixed #328 #329

### CODE REVIEW

**Comment by tpaviot** [comment]
@jf--- I disagree with selection orange by default. I can't see anything selected, it's blended with shape color. This is not related with #328 and #329.

**Comment by tpaviot** [comment]
see attached screenshot why orange selection color is bad
capture
The draw option boundary is quite cool !

**Comment by jf---** [comment]
OK, I'll comment out the selection color, rather than delete it... happy to hear you like the boundary option too...

**Comment by tpaviot** [comment]
@jf--- The selection color orange is already commented out in OCCViewer.py, not need to do it twice (see https://github.com/tpaviot/pythonocc-core/blob/master/src/addons/Display/OCCViewer.py#L148).

**Comment by jf---** [comment]
Yes, so reverted to that state in this commit

**Comment by tpaviot** [comment]
ok I see

wrt the selection color should be moved to another issue ticket "default colors", that would change default background color, default shape color as well as default selection color. We must ensure all of them produce a nice rendering. I agree that current default colors are quite old and that new colors would be welcome.

**Pull request merged**
