### PR TITLE
jf/refactor_overpaint

### LINKED ISSUE #171: overpaint example fails to overpaint when re-orienting ( panning, rotating ) the view
So the following actions invoke the OpenGL window to be re-drawn:

ON_ZOOM 
ON_ZOOM_AREA 
ON_ZOOM_FACTOR 
ON_ZOOM_FITALL 
ON_DYN_ZOOM 
ON_DYN_ROT 
ON_DYN_PAN 
ON_MOVE_TO 
ON_SHIFT_SELECT 
ON_SELECT 
ON_SELECT_AREA 

Now, when you perform any of these commands, say you're zooming or panning, this will interfere with the overpainting on top of the OpenGL window.

So, there's a lack of coordination between actions that invoke the OpenGL window to be redrawn.
The way things work in Qt is that when you call the __update__ method, that all OpenGL actions are performed in the correct order, that is, overpainting the view comes last.

So rather than having the action performed directly ( eg, unorchestrated ), the command is registered as the current action and all redrawing is performed with the __paintEvent__ method, following the Qt idiom.

I guess its best to provide an example: here's  how I've re-implemented the overpaint examples __mouseMoveEvent__:

```python
    def mouseMoveEvent(self, event):
        print("mouse move")
        self.point_on_mouse_move = event

        buttons = int(event.buttons())
        modifiers = event.modifiers()

        # rotate
        if buttons == QtCore.Qt.LeftButton and not modifiers == QtCore.Qt.ShiftModifier:
            self.current_action = ON_DYN_ROT

        # dynamic zoom
        elif buttons == QtCore.Qt.RightButton and not modifiers == QtCore.Qt.ShiftModifier:
            self.current_action = ON_DYN_ZOOM

        # dynamic panning
        elif buttons == QtCore.Qt.MidButton:
            self.current_action = ON_DYN_PAN

        # zoom window, overpaints rectangle
        elif buttons == QtCore.Qt.RightButton and modifiers == QtCore.Qt.ShiftModifier:
            self.current_action = ON_ZOOM_AREA

        # select area
        elif buttons == QtCore.Qt.LeftButton and modifiers == QtCore.Qt.ShiftModifier:
            self.current_action = ON_SELECT_AREA
       
       # -> this invoked self.paintEvent, following the Qt idiom
        self.update()
```

### PR DESCRIPTION
**Pull request by jf---**
overpaint example fails to overpaint when re-orienting ( panning, rotating ) the view 

fixes #171

### CODE REVIEW

**Comment by tpaviot** [comment]
It still flickers on Windows but I guess it's not the purpose of this patch. Could you please add a line ending at the end of the file ?

**Comment by tpaviot** [comment]
After you added the line ending, +1 for merging.

You will rebase the pyQt5 branch on master so that we can see pyQt5 related changes.

**Comment by jf---** [comment]
hi @tpaviot ,

Thanks, happy to hear you like the suggested changes and thanks for the feedback wrt windows, that's a bit dissapointing to hear, but indeed, I had not tested this.

Actually, in the [other PR](https://github.com/tpaviot/pythonocc-core/pull/175/files) this example was updated with the changes for pyqt5... 

Let me close this PR and lets continue the discussion over there...
Come to think of it, these completely overlap...

**Comment by tpaviot** [comment]
I think it's better to first merge this contribution, related to overpainting, and then process the pyqt5 upgrade. These are different things, and I'm not sure the second one can be merged as is.

**Comment by jf---** [comment]
OK, actually that was the thinking for the 2 different PR's :sunglasses:

**Comment by tpaviot** [comment]
I merged the branch, did some small pep8 modif (line length mostly), and merged all commits into one: 308963fa83d952621b6748716eb47c8ffbb118f8

**Comment by jf---** [comment]
@tpaviot , what tool are you using? I've tried autopep8, but whatever you do / use has much better results...

**Pull request merged**
