### PR TITLE
Adding a layer management tool to pythonocc

### PR DESCRIPTION
**Pull request by Tanneguydv**
I propose an example file in another pull request (pythonocc-demos) along with this one

### CODE REVIEW

**Comment by tpaviot** [comment]
Very good idea. The ```create``` and ```add``` methods look very similar. I suggest that the ```create``` method is removed, add a parameter to the ```__init__``` and call ```add``` from it. That could look like:

```python
class Layer:  # no need for parenthesis

    def __init__(self, from_shape=None, color=0):
        self.clear()
        if shape is not None:
            self.add(shape, color)
```

**Comment by rainman110** [comment]
@Tanneguydv Currently, your code assumes ``display`` as a global variable, which might not always be the case. I suggest to add a display argument to the layer constructor.

**Comment by Tanneguydv** [comment]
@tpaviot Indeed, the two functions were redundants, But I prefer to keep the color argument in the init section so that each layer has its  own color

@rainman110 True, I was thinking of this as most of the time display = self.display

Thank you,
here what I suggest :
```
class Layer:

    def __init__(self, from_display, shape=None, color=0):
        self.clear()
        self.color = color
        self.display = from_display
        if shape is not None:
            self.add(shape)

    def show(self):
        for shape in self.list_to_display:
            self.display.Context.Display(shape, True)

    def hide(self):
        for shape in self.list_to_display:
            self.display.Context.Erase(shape, False)

    def add(self, shape):
        self.to_display = {self.count}
        self.to_display = self.display.DisplayShape(shape, color=self.color)[0]
        self.list_to_display.append(self.to_display)
        self.count += 1
        self.display.Context.Erase(self.to_display, False)

    def clear(self):
        self.list_to_display = []
        self.count = 0
        self.to_display = {self.count}
```

if ok, I would change my pull request and adapt the example file in the pythonocc-demos repo

**Comment by Tanneguydv** [comment]
I added two methods to the pull request : join layers, and get_shapes from layer

**Pull request merged**
