### PR TITLE
Supports PySide6 & Implements zoom_at_cursor

### PR DESCRIPTION
**Pull request by ovo-Tim**

### CODE REVIEW

**Comment by tpaviot** [comment]
which issue does this PR solve?

**Comment by ovo-Tim** [comment]
There may still are some bugs,don't merge it.

**Comment by ovo-Tim** [comment]
OK,there isn't any bug,you can merge ir now.

**Comment by ovo-Tim** [comment]
@tpaviot Can you merge this request as soon as possible?🙏

**Comment by ovo-Tim** [comment]
@tpaviot Could you please check and give us reply soon?🙏🙏🙏

**Comment by ovo-Tim** [comment]
This feature is enabled by default,you can use `qtDisplay.qtViewer3d().zoom_at_cursor = False` to disable this feature

**Comment by ovo-Tim** [comment]
@tpaviot ，please give feedback as soon as possible, your quick action will be highly appreciated!

**Comment by ovo-Tim** [comment]
Using [qtpy](https://github.com/spyder-ide/qtpy) maybe the best way to support PyQt5/6 and PySide2/6 instead of `backend.py`.
But `qtpy` don't support `wxPython`.

If you want to use `qtpy`,I can write some code to compatible with old apis.

**Pull request closed without merging**
