### PR TITLE
added sprocket example, related to #325

### PR DESCRIPTION
**Pull request by tpaviot**
capture

@chentao807 please check everything is ok, I just changed a few things

### CODE REVIEW

**Comment by chentao807** [comment]
@tpaviot, Sorry for my late reply, Proxy class needs improvement.
https://gist.github.com/chentao807/53e025c3a0c7028636849b68f35ce2f1

**Comment by jf---** [comment]
hi @chentao807 , thanks for the improvements! are you comfortable opening up a pull request? this way, you show up in the commit history. many people value this so we'd like to be careful with this. if too much trouble we'll just update & commit your latest version. just making sure we go about it the right way ;)

**Comment by tpaviot** [comment]
@jf--- the pr is currently opened; I'd rather like @chentao807 to provide a diff rather than a gist

**Comment by jf---** [comment]
@tpaviot , its better practice to use the PR by the contributor rather than to make another... @chentao807  just opened a PR....

**Comment by tpaviot** [comment]
@jf--- It's better practice to open the PR by yourself if ever the contributor only submit a gist.

**Comment by chentao807** [comment]
@jf--- sorry , it's my  first RP, i never did that before

**Comment by tpaviot** [comment]
@chentao807 no problem, everything is ok, thank you for your contribution

**Comment by jf---** [comment]
@chentao807 no worries, we're here to help 👍

**Pull request merged**
