### PR TITLE
jf/glsl_shader

### PR DESCRIPTION
**Pull request by jf---**
example for GLSL support

### CODE REVIEW

**Comment by jf---** [comment]
hi @tpaviot , here's a fresh, rebased PR...

**Comment by jf---** [comment]
requiring a rebase?
i think this effort is still relevant, why closing it?

**Comment by tpaviot** [comment]
It's a WIP, I guess opening an issue is better, no need to create a pull request. Open the PR when code s ready to be merged. There's also a big work to do on the history so that it's possible to review the contribution.

**Comment by jf---** [comment]
OK sure thing...
That makes sense, I'll post the example code there...

**Pull request closed without merging**
