### PR TITLE
Update wxDisplay.py

### PR DESCRIPTION
**Pull request by paddy-r**
Thomas: this now runs nicely, I removed BeginDrawing and EndDrawing as they have apparently been deprecated and didn't do anything anyway (according to Robin here: http://wxpython-users.1045709.n5.nabble.com/Python-crashes-with-3-0-0-td5720863.html), and changed DrawRectangleRect to simply DrawRectangle.

### CODE REVIEW

**Comment by tpaviot** [comment]
Could you please merge those three commits into one single commit ?

**Comment by paddy-r** [comment]
I'll do another pull request, as unable to merge commits at my end.

**Comment by paddy-r** [comment]
Can you merge them at your end? I don't have write access.

**Comment by paddy-r** [comment]
Apols Thomas, I should have made a single commit. This is my first pull request so I am learning! Github tells me that I can't merge them because I don't have write access. Can you merge them? If not, I can delete my repo and start again.
Hugh

________________________________________

**Comment by Irev-Dev** [comment]
@paddy-r by merge I think tpaviot mean rewrite your commit history so that your PR is a single commit.
Look up the docs for rebase but the steps should be

`git rebase -i master`

git will open up in your default and editor, your three commits with instructions in comments.
leave the first/top commit the rest change the keyword at the start of the commit from "pick" to "f" for "fix up" then save and close this file. git we squash all of your changes into a single commit. Because you have re-written git history you will then need to 

`git push --force`

This PR should auto update.

**Pull request merged**
