### PR TITLE
Add numpy support to OCC array types; fixes in Qt backend

### PR DESCRIPTION
**Pull request by jnwalther**
This PR adds support to convert selcted OCC array types to numpy and vice versa. Array types covered are found on the Poly, TColgp, TColStd and TShort modules in OCC.Core. The interface is implenented via the `from_numpy_array` and `to_numpy_array` methods. Additionally, fast evaluation of Geom[2d]_Curve and Geom_Surface objects using numpy is provided, via the `eval_numpy_array` method.

Tests for the numpy interfaces are provided in [test/test_core_numpy.py](https://github.com/tpaviot/pythonocc-core/compare/master...jnwalther:pythonocc-core:master?expand=1#diff-cd6c28ced6a426041b12b90045f01ec6bf2390e75385cadc07d296a977d66b11).

Furthermore, two minor fixes to the Qt backend are supplied related to #1363 and a side-effect where the global log level is inadvertently changed.

Tests are provided in [test/test_display_sideeffects.py](https://github.com/tpaviot/pythonocc-core/compare/master...jnwalther:pythonocc-core:master?expand=1#diff-1e547af6a291a506ca0ae791f9b6933000d8cd9d5c56c09d147bc61bc1847cc8).

## Summary by Sourcery

Introduce numpy support for selected OCC array types and enhance Geom[2d]_Curve and Geom_Surface evaluation with numpy. Fix minor issues in the Qt backend and add corresponding tests.

New Features:
- Add support for converting selected OCC array types to and from numpy arrays, covering modules such as Poly, TColgp, TColStd, and TShort in OCC.Core.
- Implement fast evaluation of Geom[2d]_Curve and Geom_Surface objects using numpy via the eval_numpy_array method.

Bug Fixes:
- Fix issues in the Qt backend related to global log level changes and other minor bugs.

Tests:
- Add tests for the new numpy interfaces in test/test_core_numpy.py.
- Include tests for the Qt backend fixes in test/test_display_sideeffects.py.

### CODE REVIEW

**Comment by jnwalther** [comment]
Thanks @jf---. I hope everything will work out. I'm slightly concerned about the issues reported by codacy. As far as I'm aware assert statements are commpn practice in pytest-style tests.

**Comment by jnwalther** [comment]
Ok, so it seems there is an issue with the new display tests on the Ubuntu machines. I tried to reproduce the error running on my personal Linux laptop (not Ubuntu but Arch), but I couldn't, so I doubt it's a general Linux issue. From the error message I gather that it has something to do with the way Qt is set up on the system.

My suggestion would be to simply skip the tests for linux platform. I couldn't find any indication that the previously existing core_display_* unittests were running, so I'm not even sure if the tests would have worked in the first place. What do you guys think?

To fix the assert topic [this](https://github.com/quark-engine/quark-engine/issues/256) looks promising.

**Comment by tpaviot** [comment]
Thank you for this huge work @jnwalther I need time to review your contribution and add it as a rule to the pythonocc-generator

**Comment by jnwalther** [comment]
Thank you @tpaviot, please take your time. Let me know if you have any questions.

**Pull request merged**
