### PR TITLE
Fixed issue #259

### PR DESCRIPTION
**Pull request by rainman110**
Reason for the segfault was calling strlen on a null pointer string. I changed the code to be more robust using std::strings.

Fixes issue #259

### CODE REVIEW

**Comment by tpaviot** [comment]
Perfect, that works. I was far far away to imagine the issue comes from the string code. Thanks !

**Comment by jf---** [comment]
Wow, that's fantastic that this critical issue has been solved in _such_ short notice!
Gents, should we include a unittests such to catch regressions? ( the gp_Dir().Coord(-1) is perhaps reasonable succinct )

**Comment by rainman110** [comment]
Yes, a small test case would be definetely a good idea. :+1:

**Comment by tpaviot** [comment]
Yes @jf--- a unittest is necessary, thanks for taking care of that

**Comment by jf---** [comment]
Coming up...

**Pull request merged**
