### PR TITLE
fixed #350 missing Graphic3d_Camera example

### LINKED ISSUE #350: Graphic3d_ClipPlanes and Graphic3d_Camera example
#301 was fixed. We need an example in order to show how to use these classes. This example will be run as a unittest by our run_example_as_tests suite.

### PR DESCRIPTION
**Pull request by jf---**
fixed #350 missing Graphic3d_Camera example

### CODE REVIEW

**Comment by tpaviot** [comment]
good, that works on my machine. Perhaps the 'doit' function coulb renamed to something more explicit, like "change_viewpoint" or "animate_viewpoint".

**Comment by jf---** [comment]
yeah that makes sense... thanks

**Comment by tpaviot** [comment]
@jf--- This example has to be removed from the run_example_as_tests suite, otherwise it makes travis fail

**Comment by tpaviot** [comment]
@jf---  Ok, I amended your commit here df190caaa3e606510d25e1255c54927753ae39ad

closing this PR

**Pull request closed without merging**
