### PR TITLE
jf/signals_slots_example

### PR DESCRIPTION
**Pull request by jf---**
signal/slot example

### CODE REVIEW

**Comment by tpaviot** [comment]
@jf--- please check travis log to see what's wrong

**Comment by jf---** [comment]
```bash
  File "../examples/core_display_signal_slots.py", line 12, in <module>
    QtCore, QtGui, QtWidgets, QtOpenGL = get_qt_modules()
  File "/Users/travis/miniconda/envs/_test/lib/python2.7/site-packages/OCC/Display/backend.py", line 238, in get_qt_modules
    raise ValueError("no backend has been imported yet with "
ValueError: no backend has been imported yet with ``load_backend``... 
[failed]
```
OK, need to be more careful with loading the GUI...

**Comment by jf---** [comment]
@tpaviot passing CI ;)

**Comment by tpaviot** [comment]
@jf--- I'm not convinced by this fix. There should not be any Travis specific behaviour, otherwise we can't predict how it will run on our machines. The test has to be run
Is this example qt5 specific ?

**Comment by jf---** [comment]
@tpaviot , yes its Qt specific...
so i understand that when running the test, a 'null' backend is loaded, sidestepping any gui side-effects? moreover, this example requires you to click... i think integrating CI here is a little academic?

**Comment by tpaviot** [comment]
@jf--- My question was is it qt *5* specific ? i.e does it work only with qt5 or for both qt4/qt5 ? A clean CI is a major achievement of the past months, I really want everything to be tested on travis

**Comment by jf---** [comment]
@tpaviot , no doubt the CI work is a *huge* deal 🏆 
it could work on both qt4 and qt5, yep...

i'm really not very happy with our scruffy qt ( 4, 5, pyside ) abstraction... its hard to test ( requires 3 platforms to checkout )

let's use [qtpy](https://github.com/spyder-ide/qtpy) which is really the right way of doing so...
the > 250 commits tell us its not easy to get right ;)

are you OK if i start abstracting Qt like this? really dislike our own solution...

**Comment by tpaviot** [comment]
Adding another dependency is not a priority. So far, the qt abstraction just works, to me it's ok. There are many other WIP (I think about the GLSL work, the QML example you promised a long time ago ;-) ).

**Comment by jf---** [comment]
OK, on it ;)

Yes, the QML stuff is really exciting 🚀 

image

Imagine how cool it could look with GLSL shader 🎱

**Comment by tpaviot** [comment]
@jf---  Maybe soon a blog post about this work ?

**Comment by jf---** [comment]
@tpaviot , yes, this would be fun to write about... 
it'll still take me a few weeks to complete it...
thanks for the invite...

**Comment by tpaviot** [comment]
@jf--- Can you please move the line `from OCC.Display.backend import get_qt_modules` *after* the display is initialized. I think this will make travis pass, no need to bypass it.

**Comment by jf---** [comment]
OK, 1st thing tomorrow, thanks for the heads up!

**Comment by tpaviot** [comment]
@jf--- No, after all, you should tell pythonocc to remove this test from the list of tests to exclude from run_example_as_text. For that, you just have to add core_display_signal_slots.py to https://github.com/tpaviot/pythonocc-core/blob/master/test/run_examples_as_tests.py#L30

After that, you can rebase -i onto master to remove commit fd83726

I'll merge as soon as it is done

**Comment by jf---** [comment]
coming up, thanks for the detailed explanation...l

**Comment by jf---** [comment]
`The job exceeded the maximum time limit for jobs, and has been terminated`, 1/6 fine otherwise

**Comment by tpaviot** [comment]
@jf--- It uses to occur on travis, I generally have to manually trigger another build.

**Pull request merged**
