### PR TITLE
jf/meshvs-example

### PR DESCRIPTION
**Pull request by jf---**

### CODE REVIEW

**Comment by tpaviot** [comment]
This example requires the SMESH wrapper but it's not maintained anymore.

-1

**Comment by jf---** [comment]
@tpaviot , I know the FreeCAD guys have patched SMESH, for OCC 6.8.0 compliance.
Shall I look into that? 
SMESH is quite popular...

**Comment by tpaviot** [comment]
@jf--- smesh used to be popular. It would actually be better to 1. update smesh 2. update the wrapper 3. contribute examples that require smesh

Keep this example on your drive, we'll need it later. In the meantime, maybe you can share it on pythonocc-contrib

I let you close the pr by yourself.

**Comment by jf---** [comment]
@tpaviot , that's what we'll do... I'll reopen this PR when we're at stage 3

**Comment by crobarcro** [comment]
Just commenting to add a vote for smesh wrapper support, it would be incredibly useful for all sorts of science and engineering applications, if it existed I would probably write a FreeCAD workbench to access it.

**Comment by jf---** [comment]
@crobarcro , yes, I share the same itch to scratch. I'll be on this tomorrow.

**Pull request closed without merging**
